<?php

return [
    'password_history_count' => 5,
    'lockout_attempts' => 5,
    'lockout_minutes' => 30,
    'reset_token_hours' => 1,
    'remember_days' => 30,
    'session_idle_minutes' => 120,
    'default_sharing' => env('CRM_DEFAULT_SHARING', 'private'),
    'case_number_prefix' => 'CAS-',
    'attachment_max_kb' => 25600,
    'attachment_mimes' => ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'txt'],
    'list_page_size' => 25,
    'list_max_page_size' => 200,

    'salutations' => ['Mr.', 'Ms.', 'Mrs.', 'Dr.', 'Prof.'],
    'lead_sources' => ['Advertisement', 'External Referral', 'Social', 'Trade Show', 'Web', 'Other'],
    'industries' => ['Agriculture', 'Apparel', 'Banking', 'Biotechnology', 'Chemicals', 'Communications', 'Construction', 'Consulting', 'Education', 'Electronics', 'Energy', 'Engineering', 'Entertainment', 'Environmental', 'Finance', 'Food & Beverage', 'Government', 'Healthcare', 'Hospitality', 'Insurance', 'Machinery', 'Manufacturing', 'Media', 'Not For Profit', 'Recreation', 'Retail', 'Shipping', 'Technology', 'Telecommunications', 'Transportation', 'Utilities', 'Other'],
    'ratings' => ['Hot', 'Warm', 'Cold'],
    'lead_statuses' => ['New', 'Working', 'Nurturing', 'Qualified', 'Unqualified', 'Converted'],
    'account_types' => ['Customer', 'Prospect', 'Partner', 'Other'],
    'opportunity_types' => ['New Business', 'Existing Business', 'Renewal'],
    'opportunity_stages' => [
        'Qualification' => 10,
        'Meeting Scheduled' => 20,
        'Proposal/Price Quote' => 65,
        'Negotiation/Review' => 80,
        'Closed Won' => 100,
        'Closed Lost' => 0,
    ],
    'case_statuses' => ['New', 'Working', 'Escalated', 'Closed'],
    'case_origins' => ['Phone', 'Email', 'Web', 'Chat'],
    'case_types' => ['Question', 'Problem', 'Feature Request'],
    'case_reasons' => ['Installation', 'Equipment Complexity', 'Performance', 'Breakdown', 'Equipment Design', 'Feedback', 'Other'],
    'priorities' => ['High', 'Medium', 'Low'],
    'task_statuses' => ['Not Started', 'In Progress', 'Completed', 'Deferred'],
    'task_priorities' => ['High', 'Normal', 'Low'],
    'show_as' => ['Busy', 'Free', 'Out of Office'],
    'sharing_levels' => ['private', 'public_read', 'public_read_write'],
    'objects' => ['leads', 'accounts', 'contacts', 'opportunities', 'cases', 'tasks', 'events'],
    'roles' => [
        'System Administrator',
        'Sales Manager',
        'Sales Representative',
        'Service Representative',
        'Read-Only User',
    ],
];
